name: workflow tp2

on: push

env:
  PROJECT_VERSION: 1.0.0

jobs:
  main_job:
    runs-on: ubuntu-latest
    steps:
      - name: version projet
        run: echo $PROJECT_VERSION

      - name: Setup Java JDK
        uses: actions/setup-java@v4.5.0

      - name: build maven no test
        run: mvn clean package -DskipTests
