name: workflow tp2

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  PROJECT_VERSION: "1.0.0"
  MAVEN_OPTS: "-DskipTests -Djar.finalName=helloworld-${PROJECT_VERSION} -Dmaven.repo.local=/home/runner/work/lib"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: version projet
        run: echo $PROJECT_VERSION

      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Setup Java JDK
        uses: actions/setup-java@v4.5.0
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: build jar
        run: mvn clean package $MAVEN_OPTS

  test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        
      - name: tests maven
        run: mvn test

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.4.3
        with:
          path: "/home/runner/work/helloworld-java/helloworld-java/target/helloworld-${PROJECT_VERSION}.jar"
          if-no-files-found: warn

